### ISSUE TITLE
Json column type not available on MariaDB

### ISSUE THREAD

**Issue by lenguyenvy1995** [bjuppa/laravel-blog#34]
Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json null, `display_full_content_in_feed` tinyint(1) null, `created_at` timestam' at line 1 (SQL: create table `blog_entries` (`id` int unsigned not null auto_increment primary key, `blog` varchar(191) not null default 'main', `publish_after` timestamp null, `slug` varchar(191) not null, `title` varchar(191) not null, `author_name` varchar(191) null, `author_email` varchar(191) null, `author_url` varchar(191) null, `image` text null, `content` text not null, `summary` text null, `page_title` varchar(191) null, `description` varchar(191) null, `meta_tags` json null, `display_full_content_in_feed` tinyint(1) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')
=>> please help me

**Comment by bjuppa** [comment]
Oh, interesting, and troublesome! I don't think MariaDB supports json columns at all... This is not good, I've only tested on MySQL, PostgreSQL & SQLite during development 😞 

You could possibly get around it for now by switching to a `text` type column for `meta_tags` in the migration file, instead of `json`.

...but as this package doesn't publish the migration file for modification, this can't be done in a persistent manner for your project. I thought I was being clever there, but it bit me 😄

**Comment by bjuppa** [comment]
I think the long-term solution for this package is to have the migrations file check if connection is for MariaDB and if so, switch to `text`.

Or just use `text` by default, and add some mechanism of actually publishing the migrations file!

**Comment by bjuppa** [comment]
Here's a package that claims to add json support for MariaDB with Laravel, I haven't tried it at all, but might be worth a look: https://github.com/ybr-nx/laravel-mariadb

**Comment by bjuppa** [comment]
@lenguyenvy1995 do you know which version of MariaDB you used when you got that error? 

These sources say it should be working from MariaDB 10.2.7 and upwards:
https://mariadb.com/kb/en/library/json-data-type/
https://github.com/laravel/framework/issues/13622
