### ISSUE TITLE
How to give permission to users to create blog posts?

### ISSUE THREAD

**Issue by amittrigma** [bjuppa/laravel-blog#7]
How to give permission to users to create blog posts or how we can create new blog post?

**Comment by bjuppa** [comment]
@amittrigma Currently there is no admin backend for editing blog posts in this package.

Yet... the plan is to add that option using https://github.com/kontenta/kontour but that's for next month in my time plan.

So currently you'll need to create your own CRUD admin routes to edit `Bjuppa\LaravelBlog\Eloquent\BlogEntry` model instances (with permissions etc).

Actually, the recently announced [Laravel Nova](https://nova.laravel.com) by Taylor himself would be great for that too, but that's also not released another month from now :)

**Comment by amittrigma** [comment]
I'm getting error:
`Add [title] to fillable property to allow mass assignment on [Bjuppa\LaravelBlog\Eloquent\BlogEntry].`

My Controller function:

```
public function create(){
        \Bjuppa\LaravelBlog\Eloquent\BlogEntry::create([
            'title' => 'The first post',
            'content' => 'This is the main content of the first post',
            'publish_after' => now(),
        ]);
    }
```

**Comment by bjuppa** [comment]
@amittrigma The `BlogEntry` Eloquent model doesn't support [mass assignment](https://laravel.com/docs/5.6/eloquent#mass-assignment) and I'm not sure I want it to do that just yet. I need to think about the implications first.

For now you can create posts using the ["normal" assignment](https://laravel.com/docs/5.6/eloquent#inserting-and-updating-models) even if you can't do it all in one line with that.

The reason the code you tried works in the database seeder where you found it is because mass assignment protection is automatically disabled during database seeding in Laravel, see https://laravel.com/docs/5.6/seeding#writing-seeders
